### PR TITLE
Fix for #6

### PR DESCRIPTION
**Pull request by twnlink**
I did submit this PR before but I have updated it to suit #6, should fix issues with that. Please merge!

### CODE REVIEW

**Comment by DashLt** [comment]
this commit would fit far better on your own extension: thoughts?

**Comment by twnlink** [comment]
as far as I can tell, the yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy org does not have an extension?

**Comment by DashLt** [comment]
my apologies, I suppose the organization I was thinking of is completely and utterly irrelevant then

**Comment by twnlink** [comment]
I 100% agree, as that organization does not want to affiliate with the Cuntcil

**Pull request closed without merging**
